### ISSUE TITLE
Придумать, согласовать протокол взаимодействия с фронтендом

### ISSUE THREAD

**Issue by Wooshey1411** [Concerts-Mate/Backend#5]
2 недели.

**Comment by pipichinka** [comment]
# Регистрация пользоввателя
POST /reg
{
	"telegramId": telegram id(string)
}
регистрация прошла успешно: 
200

при регистрации обнаружился дупликат пользователя:
409 conflict

при регистрации произошла ошибка на стороне сервера:
503


# добавление города
POST /city
{
	"telegramId": telegram id(string)
	"city": city(string)
}
название города корректно:
200

название города неточно:
409
{
	"option":city(string)
}

название города некорректно:
406

telegramId нет в базе данных:
404

при регистрации произошла ошибка на стороне сервера:
503

# добавление playlist
POST /playlist
{
	"telegramId": telegram id(string)
	"link": link(string)
}
playlist успешно добавлен
200

telegramId нет в базе данных:
404

playlist link некорректна:
406

при регистрации произошла ошибка на стороне сервера:
503

# запрос текущих концертов
GET /concerts/{telegramId}

успех:
200
{
	"concerts": [
		как у Кирилла
	]
}

telegramId нет в базе данных:
404

ошибка на стороне сервера:
503

# автоматическая отправка концертов боту
POST /event/data
{
	"entities":[
		{
			"telegramId": String
			"concert": как у Кирилла
		}
	]
}

концерты успешно разосланы:
200

произошла ошибка при отправке концертов (нет интернета):
503 

произошла ошибка при отправке отдельным клиентам:
499
{
	"clients":[
		{
			"telegramId": (string)
		}
	]
}


# Удаление playlist
DELETE /playlist
{
	"telegramId": telegram id(string)
	"link": link(string)
}

успешно удалён
200

произошла ошибка на стороне сервера
503

# Удаление города
DELETE /city
{
	"telegramId": telegram id(string)
	"city": city(string)
}

успешно удалён
200

произошла ошибка на стороне сервера
503

# Удаление пользователя
DELETE /user/{telegramId}

успешно удалён
200

произошла ошибка на стороне сервера
503

**Comment by Wooshey1411** [comment]
# Регистрация пользоввателя
## F >>> B
POST /reg
{
	"telegramId": telegram id(string)
}
## Ответ

{
    "header": {
        "success": успешен ли запрос(boolean),
        "code": возвращаемый код(integer),
        "description": комментарий(string)
    }
}
### Коды
регистрация прошла успешно: 
200

при регистрации обнаружился дупликат пользователя:
409

при регистрации произошла ошибка на стороне сервера:
503


# Добавление города
## F >>> B
POST /city
{
	"telegramId": telegram id(string),
	"city": city(string)
}
## Ответ
{
    "header": {
        "success": успешен ли запрос(boolean)
        "code": возвращаемый код(integer)
        "description": комментарий(string)
    },
    "option": предложенный город(string)
}
### Коды
название города корректно:
200
название города неточно: 409

название города некорректно:
406

telegramId нет в базе данных:
404

при регистрации произошла ошибка на стороне сервера:
503

# добавление playlist
## F >>> B
POST /playlist
{
	"telegramId": telegram id(string),
	"link": link(string)
}
## Ответ
{
    "header": {
        "success": успешен ли запрос(boolean)
        "code": возвращаемый код(integer)
        "description": комментарий(string)
    }
}
### Коды

playlist успешно добавлен
200

telegramId нет в базе данных:
404

playlist link некорректна:
406

при регистрации произошла ошибка на стороне сервера:
503

# запрос текущих концертов
### F >>> B
GET /concerts/{telegramId}
## Ответ
{
    "header": {
        "success": успешен ли запрос(boolean)
        "code": возвращаемый код(integer)
        "description": комментарий(string)
    },
    "concerts": [
        как у Кирилла
    ]
}
### Коды
успех:
200

telegramId нет в базе данных:
404

ошибка на стороне сервера:
503

# автоматическая отправка концертов боту
## B >>> F
POST /event
{
	"entities":[
		{
			"telegramId": telegram id(string),
			"concerts": [как у Кирилла]
		}
	]
}
## Ответ
{
    "header": {
        "success": успешен ли запрос(boolean)
        "code": возвращаемый код(integer)
        "description": комментарий(string)
    }
    "clients": [
        "telegramId": telegram id(string)
    ]
}
### Коды
концерты успешно разосланы:
200

произошла ошибка при отправке концертов (нет интернета):
503 

произошла ошибка при отправке отдельным клиентам:
499

# Удаление playlist
## F >>> B
DELETE /playlist
{
	"telegramId": telegram id(string)
	"link": link(string)
}

## Ответ
{
    "header": {
        "success": успешен ли запрос(boolean)
        "code": возвращаемый код(integer)
        "description": комментарий(string)
    }
}
### Коды

успешно удалён
200

произошла ошибка на стороне сервера
503

# Удаление города
## F >>> B
DELETE /city
{
	"telegramId": telegram id(string)
	"city": city(string)
}

## Ответ
{
    "header": {
        "success": успешен ли запрос(boolean)
        "code": возвращаемый код(integer)
        "description": комментарий(string)
    }
}
### Коды

успешно удалён
200

произошла ошибка на стороне сервера
503

# Удаление пользователя
## F >>> B
DELETE /user/{telegramId}

## Ответ
{
    "header": {
        "success": успешен ли запрос(boolean)
        "code": возвращаемый код(integer)
        "description": комментарий(string)
    }
}
### Коды

успешно удалён
200

произошла ошибка на стороне сервера
503
